spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:postgresql://localhost:5432/coinverse_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jackson:
    time-zone: UTC
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
        format_sql: true
logging:
  level:
    root: info
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        jdbc:
          datasource:
            init: DEBUG
        security: DEBUG
security:
  jwt:
    secret-key: secret
  messaging:
    email-source: no-reply@coinverse.com
    sms-source: 0733001026