spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:postgresql://localhost:5432/coinverse_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jackson:
    time-zone: UTC
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
  sql:
    init:
      mode: never
      continue-on-error: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: billomailbox@gmail.com
    password: ncws agbp ruew gyyc
    properties:
      mail:
        debug: true
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    root: info
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        jdbc:
          datasource:
            init: DEBUG
        security: DEBUG
security:
  jwt:
    secret-key: secret
  messaging:
    email-source: billomailbox@gmail.com
    sms-source: 0733001026
transfer:
  properties:
    system-username: system@coinverse.com
    system-password: 123